import Link from "next/link";
import { MediaPoster } from "@/components/media/media-poster";
import { formatDuration, type ProfileStatistics } from "@/lib/profile/statistics";
import type { MovieSnapshot } from "@/lib/movies/movies";
import type { DerivedShow } from "@/lib/shows/watch-list";

const labels: Array<[keyof Pick<ProfileStatistics, "trackedShows" | "episodesWatched" | "moviesInLibrary" | "moviesWatched" | "favouriteShows" | "favouriteMovies" | "completedShows" | "caughtUpShows">, string]> = [["trackedShows", "Tracked shows"], ["episodesWatched", "Episodes watched"], ["moviesInLibrary", "Movies in library"], ["moviesWatched", "Movies watched"], ["favouriteShows", "Favourite shows"], ["favouriteMovies", "Favourite movies"], ["completedShows", "Completed shows"], ["caughtUpShows", "Caught-up shows"]];
type Favourite = { membership: { id: string }; media: { title: string; poster_path: string | null; tmdb_id: number } };
function FavouriteRail({ items, kind }: { items: Favourite[]; kind: "shows" | "movies" }) { return <ul className="mt-3 flex w-full min-w-0 gap-4 overflow-x-auto px-1 pb-3 pt-1">{items.map((item) => <li key={item.membership.id} className="w-32 shrink-0 sm:w-36"><Link href={`/${kind}/${item.media.tmdb_id}`} aria-label={item.media.title} title={item.media.title} className="poster-interactive-surface relative block aspect-[2/3] overflow-hidden rounded-xl border bg-[var(--surface-elevated)]"><MediaPoster source={item.media.poster_path} title={item.media.title} alt="" sizes="144px" /></Link></li>)}</ul>; }

export function StatisticsSummary({ statistics, shows, movies }: { statistics: ProfileStatistics; shows: DerivedShow[]; movies: MovieSnapshot[] }) {
  const times = [["Television", statistics.tvMinutes], ["Movies", statistics.movieMinutes], ["Combined", statistics.totalMinutes]] as const;
  const compareTitle = (left: Favourite, right: Favourite) => left.media.title.localeCompare(right.media.title, undefined, { sensitivity: "base" }) || left.media.tmdb_id - right.media.tmdb_id;
  const favouriteShows = shows.filter((show) => show.membership.is_favourite).sort(compareTitle);
  const favouriteMovies = movies.filter((movie) => movie.membership.is_favourite).sort(compareTitle);
  return <div className="min-w-0 space-y-8"><section><h2 className="break-words text-2xl font-semibold">Statistics</h2><dl className="mt-3 grid grid-cols-1 gap-3 min-[360px]:grid-cols-2 sm:grid-cols-4">{labels.map(([key, label]) => <div key={key} className="min-w-0 rounded-xl border border-[var(--border)] bg-[var(--surface)] p-4"><dt className="break-words text-sm text-[var(--muted)]">{label}</dt><dd className="mt-1 break-words text-2xl font-semibold">{statistics[key]}</dd></div>)}</dl></section><section><h2 className="break-words text-2xl font-semibold">Estimated watch time</h2><div className="mt-3 grid gap-3 sm:grid-cols-3">{times.map(([label, minutes]) => { const value = formatDuration(minutes); return <div key={label} className="min-w-0 rounded-xl border border-[var(--border)] bg-[var(--surface)] p-4"><h3 className="break-words font-semibold">{label}</h3><p className="mt-2 break-words text-xl font-semibold">{value.daysAndHours}</p><p className="break-words text-sm text-[var(--muted)]">{value.hours} · {value.minutes}</p></div>; })}</div></section>{favouriteShows.length ? <section><h2 className="break-words text-2xl font-semibold">Favourite shows</h2><FavouriteRail items={favouriteShows} kind="shows" /></section> : null}{favouriteMovies.length ? <section><h2 className="break-words text-2xl font-semibold">Favourite movies</h2><FavouriteRail items={favouriteMovies} kind="movies" /></section> : null}</div>;
}
