"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { removeFromLibrary } from "@/app/actions/library";
import { initializeShow, markPreviousEpisodes, setEpisodeWatched, setSeasonWatched, syncShowMetadata, updateShowSettings, updateWatchedDate, type InitialMode, type ShowActionResult } from "@/app/actions/shows";
import type { Episode, ShowTrackingStatus, UserShow, WatchedEpisode } from "@/types/database";

function ActionMessage({ result }: { result: ShowActionResult | null }) { return result ? <div aria-live="polite" className="space-y-1 text-sm">{result.error ? <p className="text-[var(--danger)]">{result.error}</p> : null}{result.success ? <p className="text-[var(--success)]">{result.success}</p> : null}{result.warning ? <p className="text-yellow-700 dark:text-yellow-300">{result.warning}</p> : null}</div> : null; }
const button = "rounded-lg border border-[var(--border)] px-3 py-2 text-sm font-semibold disabled:opacity-50";

export function MetadataButton({ tmdbId }: { tmdbId: number }) { const [pending, start] = useTransition(); const [result, setResult] = useState<ShowActionResult | null>(null); return <div><button className={button} disabled={pending} onClick={() => start(async () => setResult(await syncShowMetadata(tmdbId)))}>{pending ? "Synchronizing…" : "Refresh Metadata"}</button><ActionMessage result={result} /></div>; }

export function RemoveShowButton({ tmdbId }: { tmdbId: number }) { const router = useRouter(); const [pending, start] = useTransition(); const [result, setResult] = useState<ShowActionResult | null>(null); return <div><button className={`${button} text-[var(--danger)]`} disabled={pending} onClick={() => start(async () => { const response = await removeFromLibrary("tv", tmdbId); setResult(response); if (!response.error) router.push("/shows"); })}>{pending ? "Removing…" : "Remove from library"}</button><p className="mt-1 text-xs text-[var(--muted)]">Watch history will be preserved.</p><ActionMessage result={result} /></div>; }

export function SettingsControls({ tmdbId, mediaId, membership }: { tmdbId: number; mediaId: string; membership: UserShow }) { const [pending, start] = useTransition(); const [result, setResult] = useState<ShowActionResult | null>(null); const run = (values: { status?: ShowTrackingStatus; isFavourite?: boolean }) => start(async () => setResult(await updateShowSettings(tmdbId, mediaId, values))); return <div className="flex flex-wrap items-center gap-3"><button className={button} disabled={pending} onClick={() => run({ isFavourite: !membership.is_favourite })}>{membership.is_favourite ? "★ Favourite" : "☆ Add favourite"}</button><label className="text-sm">Status <select className="ml-2 rounded-lg border border-[var(--border)] bg-[var(--surface)] p-2" value={membership.status} disabled={pending} onChange={(event) => run({ status: event.target.value as ShowTrackingStatus })}><option value="active">Active</option><option value="paused">Paused</option><option value="dropped">Dropped</option></select></label><RemoveShowButton tmdbId={tmdbId} /><ActionMessage result={result} /></div>; }

export function InitialProgressForm({ tmdbId, episodes }: { tmdbId: number; episodes: Episode[] }) { const regular = episodes.filter((episode) => episode.season_number > 0); const seasons = [...new Set(regular.map((episode) => episode.season_number))]; const [mode, setMode] = useState<InitialMode["mode"]>("start"); const [target, setTarget] = useState(regular[0] ? `${regular[0].season_number}:${regular[0].episode_number}` : ""); const [selected, setSelected] = useState<number[]>([]); const [pending, start] = useTransition(); const [result, setResult] = useState<ShowActionResult | null>(null);
  function submit() { let selection: InitialMode = { mode: "start" }; if (mode === "before_episode") { const [seasonNumber, episodeNumber] = target.split(":").map(Number); selection = { mode, seasonNumber, episodeNumber }; } else if (mode === "seasons") selection = { mode, seasonNumbers: selected }; start(async () => setResult(await initializeShow(tmdbId, selection))); }
  return <section className="space-y-4 rounded-xl border border-[var(--border)] bg-[var(--surface)] p-5"><h2 className="text-xl font-semibold">Add show and set progress</h2><label className="block"><input type="radio" checked={mode === "start"} onChange={() => setMode("start")} /> <span className="ml-2">Start from Season 1, Episode 1</span></label><label className="block"><input type="radio" checked={mode === "before_episode"} onChange={() => setMode("before_episode")} /> <span className="ml-2">Mark everything before</span></label>{mode === "before_episode" ? <select className="w-full rounded-lg border border-[var(--border)] bg-[var(--surface)] p-2" value={target} onChange={(event) => setTarget(event.target.value)}>{regular.map((episode) => <option key={episode.id} value={`${episode.season_number}:${episode.episode_number}`}>S{String(episode.season_number).padStart(2, "0")} | E{String(episode.episode_number).padStart(2, "0")} — {episode.title}</option>)}</select> : null}<label className="block"><input type="radio" checked={mode === "seasons"} onChange={() => setMode("seasons")} /> <span className="ml-2">Select complete watched seasons</span></label>{mode === "seasons" ? <div className="flex flex-wrap gap-3">{seasons.map((season) => <label key={season}><input type="checkbox" checked={selected.includes(season)} onChange={() => setSelected((current) => current.includes(season) ? current.filter((item) => item !== season) : [...current, season])} /> Season {season}</label>)}</div> : null}<button className="rounded-lg bg-[var(--accent)] px-4 py-2 font-semibold text-[var(--accent-foreground)] disabled:opacity-50" disabled={pending || (mode === "before_episode" && !target) || (mode === "seasons" && !selected.length)} onClick={submit}>{pending ? "Synchronizing and adding…" : "Add to library"}</button><ActionMessage result={result} /></section>;
}

export function EpisodeControls({ tmdbId, mediaId, episode, watched }: { tmdbId: number; mediaId: string; episode: Episode; watched: WatchedEpisode | undefined }) { const [pending, start] = useTransition(); const [result, setResult] = useState<ShowActionResult | null>(null); const released = episode.air_date !== null && episode.air_date <= new Date().toISOString().slice(0, 10); const dateValue = watched?.watched_at.slice(0, 16) ?? ""; return <div className="flex flex-wrap items-center gap-2"><button className={button} disabled={pending || (!watched && !released)} onClick={() => start(async () => setResult(await setEpisodeWatched(tmdbId, mediaId, episode.id, !watched)))}>{pending ? "Saving…" : watched ? "Mark unwatched" : released ? "Mark watched" : "Unreleased"}</button>{watched ? <><input aria-label="Watched date" type="datetime-local" defaultValue={dateValue} max={new Date().toISOString().slice(0, 16)} className="rounded-lg border border-[var(--border)] bg-[var(--surface)] p-2 text-sm" id={`date-${episode.id}`} /><button className={button} disabled={pending} onClick={() => { const input = document.getElementById(`date-${episode.id}`); if (input instanceof HTMLInputElement) start(async () => setResult(await updateWatchedDate(tmdbId, mediaId, episode.id, input.value))); }}>Save date</button></> : null}<button className={button} disabled={pending || episode.season_number === 0} onClick={() => start(async () => setResult(await markPreviousEpisodes(tmdbId, mediaId, episode.season_number, episode.episode_number)))}>Mark previous watched</button><ActionMessage result={result} /></div>; }

export function SeasonControls({ tmdbId, mediaId, season }: { tmdbId: number; mediaId: string; season: number }) { const [pending, start] = useTransition(); const [result, setResult] = useState<ShowActionResult | null>(null); const run = (watched: boolean) => start(async () => setResult(await setSeasonWatched(tmdbId, mediaId, season, watched))); return <div className="flex flex-wrap gap-2"><button className={button} disabled={pending} onClick={() => run(true)}>Mark season watched</button><button className={button} disabled={pending} onClick={() => run(false)}>Mark season unwatched</button><ActionMessage result={result} /></div>; }
